version: "3"
services:
  image2html:
    restart: always
    build: .
    container_name: "image2html"
    tty: true
    privileged: true
    volumes:
      - ./notebooks:/tf/notebooks
      - ./dataset:/tf/dataset
    command: jupyter-lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --notebook-dir=/tf
    ports:
      - "8888:8888"
